version: '3'

networks:
  subnet:
    driver: bridge

services: # 컨테이너 설정
  leg3nd-agora:
    container_name: leg3nd-agora
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - subnet
  mysql:
    image: mysql:8.0.32
    restart: always
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=agora
    ports: # -p 옵션과 동일
      - "3306:3306"
    networks:
      - subnet