// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"leg3nd-agora/internal/api"
	"leg3nd-agora/internal/core/service"
	"leg3nd-agora/internal/repository"
)

// Injectors from server.go:

func New() (*fiber.App, func(), error) {
	client, cleanup, err := repository.ProvideClient()
	if err != nil {
		return nil, nil, err
	}
	accountRepository := repository.ProvideAccountRepository(client)
	accountService := service.ProvideAccountService(accountRepository)
	accountHandlers := api.ProvideAccountHandlers(accountService)
	app := ProvideApp(accountHandlers)
	return app, func() {
		cleanup()
	}, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
